# -*- coding: utf-8 -*-
"""큰 수의 법칙

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kt7pUvM2vfptqnY5MX2a0EB_EOkVuA3b

혼자 풀기
"""

n, m, k = map(int, input().split())
num_list = list(map(int, input().split()))

num_list = sorted(num_list, reverse = True)

sum = 0
while m:
  if m >= k+1:
    sum = sum + (num_list[0]*k) + num_list[1]
    m = m-(k+1)
  elif m == k:
    sum = sum + num_list[0]*k
    m = 0
  else:
    sum = sum + num_list[0]*m
    m = 0

print(sum)

"""최적화"""

n, m, k = map(int, input().split())
num_list = list(map(int, input().split()))

num_list.sort(reverse = True)
first = num_list[0]
second = num_list[1]

cnt = (m//(k+1)) * k
cnt += m%(k+1)

sum = cnt*first
sum+= (m-cnt)*second

print(sum)